name = "MaquiTracker"
uuid = "134b6fcf-ba1f-410c-8d54-0e9b83ab16ce"
authors = ["charfield"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
